#!/bin/bash

#SBATCH --job-name=v1_openmp_matmul
#SBATCH --qos=6hours
#SBATCH --partition=scicore
#SBATCH --time=06:00:00
#SBATCH --hint=nomultithread
#SBATCH --mem=80G
#SBATCH --output=logs/v1_openmp_matmul-%j.out

set -euo pipefail

cd /scicore/home/s-gpu-course/course_gpu_10/project/Mat_Mul/v1_openmp

module purge
ml CMake/4.0.3-GCCcore-14.3.0

OUTPUT_DIR=${OUTPUT_DIR:-openmp_matmul_results}

mkdir -p compiled logs "${OUTPUT_DIR}"

BIN=compiled/build-matmul-openmp-${SLURM_JOB_ID}

export OMP_NUM_THREADS=${THREADS}
# export OMP_PROC_BIND=${OMP_PROC_BIND:-spread}
# export OMP_PLACES=${OMP_PLACES:-cores}


cmake -S . -B "${BIN}" -DCMAKE_BUILD_TYPE=Release
cmake --build "${BIN}" -j "${SLURM_CPUS_PER_TASK}"

srun "${BIN}/v1_openmp_matmul" "${OUTPUT_DIR}" "${M}" "${N}" "${THREADS}" "${REP}"

